import datetime as dt
import random
from time import sleep

from selenium import webdriver


def auto_racetrac_survey() :
    yesterday = dt.datetime.now() - dt.timedelta(days=1)
    yesterday_as_str = yesterday.strftime('%m/%d/%Y')
    money_spent = random.randint(107, 999) / 100
    transaction_number = random.randint(2222222, 7777777)
    driver = webdriver.Chrome()
    driver.get('http://www.tellracetrac.com/')
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_173894_74647')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    store_text = driver.find_element_by_id('promptInput_125225')
    store_text.send_keys('64')
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    date_text = driver.find_element_by_id('promptInput_53873')
    date_text.send_keys(yesterday_as_str)
    cost_text = driver.find_element_by_id('promptInput_54006')
    cost_text.send_keys(str(money_spent))
    radio = driver.find_element_by_id('option_232296_99512')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_126584_53811')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_127134_54080')
    driver.execute_script('arguments[0].click();', radio)
    transaction_text = driver.find_element_by_id('promptInput_53872')
    transaction_text.send_keys(str(transaction_number))
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_205005_88170')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_205018_88171')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_205035_88172')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_205044_88173')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_205053_88174')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_205058_88175')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_205085_88197')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_232866_99802')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_602566_276641')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_602568_276642')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602581_276647')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602605_276652')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602627_276659')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602649_276666')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602671_276673')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602693_276680')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_205891_88582')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_232281_99509')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_232865_98525')
    driver.execute_script('arguments[0].click();', radio)
    radio = driver.find_element_by_id('option_243196_104952')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_602695_276682')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(1)
    radio = driver.find_element_by_id('option_230393_98527')
    driver.execute_script('arguments[0].click();', radio)
    driver.find_element_by_id('nextPageLink').click()
    sleep(20)


auto_racetrac_survey()

